### PR TITLE
Added support for Stones (Genoa), Badami (Trento) and Rembrandt

### PR DESCRIPTION
**Pull request by FIFARenderZ**
Added support for new and upcoming Zen 3 (family 19h) products. 

Genoa = 00A10F00h
Trento = 00A30F00h
Rembrandt = 00A50F00h

Just a minor addition, but it helps future bios microcode extraction :)

### CODE REVIEW

**Comment by platomav** [comment]
Thank you for the pull request. Are we certain that the actual size is 0x15C0? It is very important for the AMD size to be correct/accurate, otherwise we'll end up extracting more or less (!) data.

**Comment by FIFARenderZ** [comment]
Yes, like @patrickschur mentioned, all the familiy 19h products have a size of 0x15C0

**Comment by platomav** [comment]
Yes I remember but he did not add these ones at the time and I wonder if AMD uses a different size. Better safe than sorry. Alright, I'll merge this request and will push an actual update (py + db) later today. ;)

**Comment by FIFARenderZ** [comment]
You're right, these have only just been discovered and added officially hence why he didn't add them back then. If there are any updates I'll immediately notify you. Thanks for the quick responses

**Review by platomav — APPROVED** [review]

**Pull request merged**
